### ISSUE TITLE
cardPostalCode validation bug

### ISSUE THREAD

**Issue by scottrpaterson** [stripe/elements-examples#11]
On form submit the class for 'invalid' is not added to cardPostalCode.

So for example if the form contains fields for credit card, expiration, csv, and postal code, and the form is submitted without entering any data, the invalid class is not added to the postal code input field. If the credit card field is filled in but the others are not, then the correct invalid class is applied to the postal code field.

This bug can be seen on this page: https://stripe.github.io/elements-examples/ - in example 4. Fill out the name, email and phone, but leave the other fields blank and submit the form.

**Comment by jez** [comment]
Hey @scottrpaterson! Thanks for pointing out this behavior.

First, I think you're talking about example 3 if I'm not mistaken? (aside: an actual bug, all the "View source on GitHub" links to go `#example-4`!)

I think the core of the issue is that if the customer hasn't entered a phone number, we can't tell if it's required. Stripe Elements determines whether the customer has entered a number that's issued for a country that uses postal codes.

If you try entering name, email, phone, and a partial card number of `4242424242424242` (US VISA test card) then it'll show the postal code field in red.

On the other hand, if you enter `4000000760000002` (Brazil VISA test card), it won't make postal code required.

**Comment by scottrpaterson** [comment]
Yes, I meant example 3, sorry about that. That makes sense, thanks @jez !
