### ISSUE TITLE
No way to determine if card mounted already

### ISSUE THREAD

**Issue by pretty** [stripe/elements-examples#37]
Just some feedback, we're able to track whether we mounted the card already in our vuejs app by setting a flag. The only other way to determine the state is to use something like this..

```
var elements = stripe.elements();
var card = elements.create('card');
card.mount('#card-element');
```

and then...

`if (card._parent){....`

Which isn't best practice as it's meant to be a private property and could change any time.

Would be nice to have something like...

`if (card.mounted()){...`

Thanks! 🤘

**Comment by asolove-stripe** [comment]
Hey @pretty, thanks for the feedback! 

There are a lot of things that could be meant by "when the element is mounted" which is why we don't expose this publicly. For example, having a `_parent` means that the element's container in this document is on the DOM, but the actual content (which is rendered in an iframe) may not be ready to display or receive user input.

We expect that most users will want to know not about mounting itself, but about when the element is fully rendered and ready. For this reason, we encourage listening to `card.on('ready', () => {})` since the `ready` event indicates that the element is mounted, the content has rendered, and all the js has run so it's ready to receive user input or events.

**Comment by atty-stripe** [comment]
Closing as `card.on('ready' () => {})` is the recommended way to recognize this.

**Comment by pretty** [comment]
But if you have a js framework like react or vuejs which has a virtual DOM and the element is removed but we come back it’s not longer there, how is it best to handle this? I want to be able to store the state and re attach it is that possible? I also dont want to have to remount each time the app state changes affecting the DOM which is why I suggested this

**Comment by atty-stripe** [comment]
@pretty I'm not sure I fully follow. Could you expand on your use case a bit more? What does your form look like, and how does change in app state affect rendering Elements? Ideally you would not mount and remount Elements many times, especially if the user has typed input already. You should merely show / hide it using CSS if your form needs that.
