### ISSUE TITLE
Return throwing native validation issue for Chrome

### ISSUE THREAD

**Issue by pretty** [stripe/elements-examples#44]
When pressing "return" on the keyboard, instead of submitting the form the element is showing this: http://drop.subbly.co/0e3e3R053B24

Any ideas what we can do, it's jarring in the UX. The input is correct because when I manually trigger the token generation it works. And I've tried multiple times.

**Comment by pretty** [comment]
Hi @jez it seems to be unpredictable.

When I opened dev tools and put it into mobile responsive mode this is what happened:

http://drop.subbly.co/3u3Y3U0X0Q1z

Works fine in non-mobile responsive mode

**Comment by jez** [comment]
It looks like this is an issue with your particular checkout form. In particular, I imagine you're setting a `required` attribute on the HTML element, but without seeing the source, it's hard to tell for sure.

If you need help debugging what's up, definitely reach out to our support team! 

- https://support.stripe.com/email, or
- #stripe on freenode

Since this repo is for examples of Elements usage and bugs in these particular examples, I'm going to close this.
