### ISSUE TITLE
card icon in cardNumber element instead of single line card

### ISSUE THREAD

**Issue by mcordoba** [stripe/elements-examples#49]
Hi,

Is it possible to include the card icon in a cardNumber element instead of have to use single line card element? I am trying to add it and is not possible.

I prefered the way you can customize the payment form in the previous version. This new way has more restrictions :(

I hope your answer. Thank you

**Comment by jez** [comment]
Hey there! Thanks for the feedback. Unfortunately, we do not intend to support this use case. You can listen to the `'change'` event which contains the card brand in the event payload:

https://stripe.com/docs/stripe-js/reference#element-on

You can use this change event to show your own icons.

Since this repo is just for examples of Elements usage (and bugs in these examples), I'm going to close this issue.

If you're having general trouble with Stripe.js or your Stripe integration, please reach out to us using the form at https://support.stripe.com/email or come chat with us at #stripe on freenode! We're very proud of our level of service, and we're more than happy to help you out with your integration.
