### ISSUE TITLE
Question about 'data-tid' attribute

### ISSUE THREAD

**Issue by raini35** [stripe/elements-examples#50]
`<label for="example2-card-cvc" data-tid="elements_examples.form.card_cvc_label">CVC</label>`

I was looking through the examples and noticed the 'data-tid' attribute and I was wondering what it actually does. Do I need to include that in my own code?

**Comment by jez** [comment]
👋 Hey @raini35,

That's short for "translation ID" and it's something specific to just these examples, so that we can localize the entire demo into multiple languages.

If you're not localizing your app, or you're using some other method for localization, you can omit this.

(Also: this property is a `data-*` attribute, which means it's a way to store arbitrary data on the HTML element. It doesn't have any other meaning according to the browser.)
