### ISSUE TITLE
Stripe elements autocomplete issue on mobile , overlaps fields, completely messed up 

### ISSUE THREAD

**Issue by aligajani** [stripe/elements-examples#55]
Image is here: https://media.saveeo.com/laravel/uploads/m83f4d49f5268651fa0ca84fe8ff91e5.jpeg

**Comment by cweiss-stripe** [comment]
Hi @aligajani 

The issue with that integration seems to be, that the width of the Element is way too narrow to display all its contents. Can you try to increase the width of the container, so it takes up close to the full available horizontal width on mobile?

Since this repo is just for examples of Elements usage (and bugs in these examples), I'm going to close this issue.

If you're having general trouble with Stripe.js or your Stripe integration, please reach out to us using the form at https://support.stripe.com/email or come chat with us at #stripe on freenode! We're very proud of our level of service, and we're more than happy to help you out with your integration
