### ISSUE TITLE
Is it possible to get the country from the card element?

### ISSUE THREAD

**Issue by FredFuras** [stripe/elements-examples#57]
Hi there,

I'm integrating Stripe with TaxJar as I would like to show the user their expected sales tax before they agree to pay. TaxJar requires two to three pieces of information in order to calculate the sales tax amount: the country, the state (if it's the U.S. or Canada), and the postal code. 

I'm able to provide them with a postal code (and derive a state from that postal code) by attaching an onChange event handler to the PostalCodeElement and getting the value from the event raised since the postal code is not sensitive data. However, I can't figure out how to get the country of the card. I know Stripe Elements figures that out internally (which is how it adjusts the postal code format based on the card's country) so is there some way for me to access that information from the form? That would be really helpful.

Thank you,
Fred

**Comment by mirceaciu** [comment]
You generate a card Token or Source. This object contains a lot of information, including country

**Comment by FredFuras** [comment]
Hi, yes, that's what I'm doing when the user clicks "checkout". I send the token to my server, which calls Stripe, saves the source, and uses the data from the response to derive the country the user's card is in.

But I'm talking about before that. In my application flow, the order is as follows:
1. User selects subscription (with pre-tax amounts).
2. User enters card details.
3. User sees the sales tax based on the card's location and the total after tax is applied.
4. User clicks confirmation button. At this point, I save the token with Stripe.

Between stages 2 and 3, it would be nice to be able to get the card's country. At this stage I can already get the card's postal code because I can attach an onChange handler to the PostalCodeElement field. This is before the token is ever submitted. And since I know Stripe Elements internally knows which country the card is in based on the card number (which is how it selects the postal code formatting), I'd like to also know that information. If the postal code is available and not considered to be sensitive data, then logically the country, being significantly less detailed than a postal code, should not pose a security concern either.

I'm wondering whether that functionality is already there and I simply can't figure it out, or if maybe that could be a future feature?

**Comment by FredFuras** [comment]
Thanks for trying to help out. That's correct, I need the country data before I create a source so that the user can confirm they're happy with the full total, which includes the sales tax amount.

However, I'm not using Taxamo, I'm using TaxJar. I've checked their API and they don't have `force_country_code` anywhere.

**Comment by asolove-stripe** [comment]
Hi @FredFuras: sorry for the slow reply on this. (FYI, this repo is just for some examples of styling elements, so if you have stripe.js feature questions like this you'll get a quicker answer by [contacting support](https://support.stripe.com/).)

What's said above, that country is not available until token or source, is true.

FYI, we do offer a [TaxJar integration path](https://stripe.com/docs/orders/tax-integration) that might remove the need for you to do some of the work you're describing here.

I would also mention that the country where a card was issued is generally not enough information to know what tax to charge. (Disclaimer: IANAL, and this is not official advice.) I believe that EU VAT, for example, will depend in part on shipping address and other things rather than just billing address and that you may need to explicitly collect the billing address rather than just looking at where the card was issued.
