### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by abrambailey** [stripe/elements-examples#58]
Rather than having common code and making us integrate into the example js, why not make this easier and give us the HTML, CSS, and JS that we need to recreate each example. It seems crazy to me to have this beautiful landing page and then throw people under the bus with this confusing set of examples.. I've been screwing around for an hour and still don't have a form that looks and works right.

**Comment by asolove-stripe** [comment]
Hey @abrambailey, sorry for our slow reply on this. We'd love to know more about what you're trying to accomplish and how these examples could be easier to understand. 

In particular, I hope you know that we have [regular docs and guides](https://stripe.com/docs/stripe-js/elements/quickstart) that are a much better place to start if you're just trying to get Elements to work on your page. 

These examples are more involved and harder to understand because they show relatively advanced ways to use Elements to create fancy checkout forms. Our assumption is that people might look at them for inspiration or to verify that elements can support complex designs. If there's something in particular you were hoping to learn from the examples but couldn't figure out, let us know!

**Comment by abrambailey** [comment]
I was able to get one of the examples working, eventually, but it wasn't straightforward. My suggestion is still the same.. break these examples out so they each have their own set of js and css assets rather than trying to combine them on a common js file and forcing people to figure out which parts are needed for each example.

**Comment by abrambailey** [comment]
Issue closed, no response. Guess my suggestion met a wall eh?

**Comment by asolove-stripe** [comment]
Hey @abrambailey, I apologize, I should have replied. I expected that since your case was now working that you weren't interested in discussing further. We definitely are grateful for the feedback that these examples aren't very clear and reproducible. And we do know that other customers have had trouble figuring our which configurations options they want to produce complex designs.

We have other work underway to provide clearer examples of advanced elements configurations that I think will resolve this problem, which I expect to be out soon.

**Comment by abrambailey** [comment]
You have more than redeemed yourself with that response. Especially excited to see the new examples. Cheers.
