### ISSUE TITLE
Option to disable the auto-advance cursor when using the card element

### ISSUE THREAD

**Issue by binomialstew** [stripe/elements-examples#59]
I don't think the source code for stripe.js version 3 is public, so I am leaving this issue here:

The stripe card element is really slick, overall, but there is one glaring issue with UX: Auto advancing the cursor to the next area of the input is an unexpected behavior, and in most web forms, users are accustomed to tabbing to the next field. This means that, more often than not, a user will hit tab in addition to the card element auto-advancing the cursor. Then, the user will have to go back to the input they inadvertently skipped. This results in a net detriment to UX—I would be happy to see all auto advance functionality for web forms disappear. In the misguided effort to save the user from having to use a muscle-memory keystroke, this has created more of an issue.

There are usually more problems with this functionality than just a potential double cursor advance: What if their entry is incorrect? The user usually can't backspace to get back to correct their error—now they have to click. I see this is addressed in the Stripe card element.

I was unable to find a way to disable this behavior in the card element options. **Please add an option to disable the cursor auto advance in the card element** and **consider changing the default** to be something like `autoAdvance: false`.

In the meantime, we can use separate elements for the credit card fields, but if it weren't for the auto advance, I would be very happy using the card element.

**Comment by asolove-stripe** [comment]
Hi @binomialstew, thanks for opening this issue. Everyone has felt the pain of bad auto-advance implementations and we definitely strive to avoid these problems. We also share your regretful that you were unable to use the easier card element integration because of these concerns, so I want to talk about them a little bit.

Our auto-advance implementation has some usability benefits, especially on mobile, that will make us think very hard before exposing an option to turn it off. For example, not all of the card information fields can be visible at all times on devices with narrow widths. When the customer is typing in a card number on an iPhone 6 in portrait, for example, there is only room for the card number's 16 digits. If we left the cursor at the end of the field, there would be no visible sign of what to do next. So auto-advancing when the customer is done with one field helps us animate in the next one so they know what to do next. Even without width restrictions, we find that many customers on mobile are not familiar with tabbing between fields and therefore have to go through the slow process of changing their grip on the phone into their other hand, tapping on the next field, and then changing their grip again to resume typing. Auto-advance makes that experience much better.

Now, we are very mindful of problems with auto-advance and we strive to avoid them. In particular, the second problem you mention--that customers can't backspace to fix an invalid input after being auto-advanced--is not true in our implementation. Customers who notice an error can backspace and the cursor will move into the previous field and delete its final character. In addition, many of the fields we accept have natural inline validation rules that prevent invalid input. Card numbers, for example, have a Luhn check that catches 90% of typos and we do not auto-advance while the field's value is invalid.

All of this is just to say that we are very aware of the issues with auto-advance, we use it for a specific reason that solves many usability problems that would otherwise exist, and we try to avoid the negative effects of bad auto-advance implementations.

We have not observed users having difficulty with double-tabbing in the card element in real-world usage. (Random hypothesis: because we style the element to look like only one input, people treat it that way rather than tabbing between sub-fields.) But we will keep an eye on our support tickets and log data to check that that isn't happening. And if it does become a problem, we suspect we would make our auto-advance implementation smarter (ignoring the first tab after an auto-advance for a few seconds) rather than allowing it to be turned off.
