### ISSUE TITLE
How to generate real token, use form for production?

### ISSUE THREAD

**Issue by jamminjames** [stripe/elements-examples#60]
I've adapted one of these nice examples, and have it working. However, it just generates an example token and doesn't actually show up on my Dashboard in Stripe for testing. How can I get this working and closer to production-ready?

Using other form examples, I have gotten results that show on the Dashboard, but I'm not sure what to do to get this one working. 

Thanks for any help.

**Comment by jamminjames** [comment]
Okay, I was wrong, it was getting submitted, and showing up in the Dashboard Log. I expected it to show in Events, but it wasn't. 

I did discover that you need to change the token from being displayed on the form after submission, to being included as a hidden field, to be transmitted to Stripe. For any other newbies working with these example forms, in index.js, under `if (result.token)`, take out the `example.querySelector('.token').innerText = result.token.id;` line and insert:
```
        var form$ = $("#payment-form");
        var token = response['id'];
        // insert the token into the form so it gets submitted to the server
        form$.append("<input type='hidden' name='stripeToken' value='" + token + "' />");
        // and submit
        form$.get(0).submit();
```
At least, that seems to work. If I am wrong, please correct me. Thank you!

**Comment by GeoffLedak** [comment]
I'm having the same issue as well. I tried jamminjames fix and it doesn't seem to be working.

If a Stripe employee could comment on this and provide a complete example that would show up in my dashboard, that would be nice.

@asolove-stripe

**Comment by asolove-stripe** [comment]
Hi @jamminjames and @GeoffLedak! This is a repo for our examples of ways to style elements, so it's not the fastest or most helpful way to get answers on your Stripe integration. Please contact [Stripe Support](https://support.stripe.com/) to get faster and better answers.

After calling `stripe.createToken`, you will need to send that token back to your server in order to use it to create charges. The method @jamminjames illustrates with adding it to a checkout form is one way to do that.

@GeoffLedak I'm not sure exactly what issue you're having. Our [Quickstart guide](https://stripe.com/docs/stripe-js/elements/quickstart) has everything you should need to do to create a testmode card token with Elements. If you are still having trouble, I'd recommend contacting support (above), as they can see the details of your account and give you more detailed suggestions.
